import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CardUrl from '../components/CardUrl'
import CardScore from '../components/CardScore'
import CardData from '../components/CardData'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The great integrator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The great integrator
        </h1>

        <h2>
         Results for phrase: resident evil
        </h2>

        <CardUrl 
          url='https://residentevil.fandom.com/wiki/Resident_Evil_Wiki' 
          sourceImg='https://upload.wikimedia.org/wikipedia/commons/e/ee/Fandom_heart-logo.svg'
          sourceText="Fandom Community"
          category="user generated content"
        />


        <CardScore 
          value={{min: 0, max: 100, actual: 54}}
          sourceImg='https://www.metacritic.com/images/icons/metacritic-icon.svg'
          sourceText="Metacritic"
          category="metascore"
        />
        
        <CardScore 
          value={{min: 0, max: 10, actual: 1.2}}
          sourceImg='https://www.metacritic.com/images/icons/metacritic-icon.svg'
          sourceText="Metacritic"
          category="user score"
        />   

        <CardData
          value={{name: "Resident Evil 7: Biohazard"}}
          sourceImg='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh2As7IJbpsEIC5yJHv4S-D8TJy5AMpcH5cG-pPFJ_93f9QZUQMGarSpWk_DCo8XKBHl0&usqp=CAU'
          sourceText="GiantBomb"
          category="aliases"
        /> 

        <CardData
          value={{name: "Resident Evil", year: 1996, publisher: "Marvel"}}
          sourceImg='https://comicvine.gamespot.com/a/bundles/comicvinesite/images/logo.png'
          sourceText="ComicVine"
          category="comics"
        />

      </main>

      <footer className={styles.footer}>    
        Powered by fandom
      </footer>
    </div>
  )
}
